# Form implementation generated from reading ui file 'RegistrationWindowUi.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegistrationWindow(object):
    def setupUi(self, RegistrationWindow):
        RegistrationWindow.setObjectName("RegistrationWindow")
        RegistrationWindow.resize(800, 640)
        RegistrationWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=RegistrationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.BackgroundImg = QtWidgets.QLabel(parent=self.centralwidget)
        self.BackgroundImg.setText("")
        self.BackgroundImg.setScaledContents(True)
        self.BackgroundImg.setObjectName("BackgroundImg")
        self.gridLayout.addWidget(self.BackgroundImg, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(361, 621))
        self.widget.setMaximumSize(QtCore.QSize(361, 621))
        self.widget.setStyleSheet("background-color: rgba(255, 255, 255, 135);\n"
"border-radius: 20px;")
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ConfBtn = QtWidgets.QPushButton(parent=self.widget)
        self.ConfBtn.setGeometry(QtCore.QRect(80, 590, 202, 21))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.ConfBtn.setFont(font)
        self.ConfBtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.ConfBtn.setObjectName("ConfBtn")
        self.SignUpText = QtWidgets.QLabel(parent=self.widget)
        self.SignUpText.setGeometry(QtCore.QRect(104, 81, 154, 31))
        font = QtGui.QFont()
        font.setFamily(".Lucida Grande UI")
        font.setPointSize(25)
        self.SignUpText.setFont(font)
        self.SignUpText.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.SignUpText.setObjectName("SignUpText")
        self.DataCheck = QtWidgets.QCheckBox(parent=self.widget)
        self.DataCheck.setGeometry(QtCore.QRect(27, 421, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.DataCheck.setFont(font)
        self.DataCheck.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.DataCheck.setChecked(False)
        self.DataCheck.setObjectName("DataCheck")
        self.PhoneNumberBox = QtWidgets.QLineEdit(parent=self.widget)
        self.PhoneNumberBox.setGeometry(QtCore.QRect(27, 241, 308, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PhoneNumberBox.setFont(font)
        self.PhoneNumberBox.setToolTipDuration(-1)
        self.PhoneNumberBox.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid #E9E9E9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.PhoneNumberBox.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.PhoneNumberBox.setObjectName("PhoneNumberBox")
        self.SignUpBtn = QtWidgets.QPushButton(parent=self.widget)
        self.SignUpBtn.setGeometry(QtCore.QRect(27, 531, 308, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SignUpBtn.setFont(font)
        self.SignUpBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.SignUpBtn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #2883CD;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: #2A8BD9;\n"
"    font-weight: bold;\n"
"}")
        self.SignUpBtn.setObjectName("SignUpBtn")
        self.ConfCheck = QtWidgets.QCheckBox(parent=self.widget)
        self.ConfCheck.setGeometry(QtCore.QRect(27, 471, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ConfCheck.setFont(font)
        self.ConfCheck.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.ConfCheck.setChecked(False)
        self.ConfCheck.setObjectName("ConfCheck")
        self.PasswordBox = QtWidgets.QLineEdit(parent=self.widget)
        self.PasswordBox.setGeometry(QtCore.QRect(27, 361, 308, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PasswordBox.setFont(font)
        self.PasswordBox.setToolTipDuration(-1)
        self.PasswordBox.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid #E9E9E9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.PasswordBox.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.PasswordBox.setObjectName("PasswordBox")
        self.BackBtn = QtWidgets.QPushButton(parent=self.widget)
        self.BackBtn.setGeometry(QtCore.QRect(21, 21, 64, 64))
        self.BackBtn.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.BackBtn.setText("")
        self.BackBtn.setObjectName("BackBtn")
        self.BirthdateBox = QtWidgets.QLineEdit(parent=self.widget)
        self.BirthdateBox.setGeometry(QtCore.QRect(27, 181, 308, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BirthdateBox.setFont(font)
        self.BirthdateBox.setToolTipDuration(-1)
        self.BirthdateBox.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid #E9E9E9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.BirthdateBox.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.BirthdateBox.setObjectName("BirthdateBox")
        self.FIOBox = QtWidgets.QLineEdit(parent=self.widget)
        self.FIOBox.setGeometry(QtCore.QRect(27, 121, 308, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.FIOBox.setFont(font)
        self.FIOBox.setToolTipDuration(-1)
        self.FIOBox.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid #E9E9E9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.FIOBox.setText("")
        self.FIOBox.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.FIOBox.setObjectName("FIOBox")
        self.SNILSBox = QtWidgets.QLineEdit(parent=self.widget)
        self.SNILSBox.setGeometry(QtCore.QRect(27, 301, 308, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SNILSBox.setFont(font)
        self.SNILSBox.setToolTipDuration(-1)
        self.SNILSBox.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid #E9E9E9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.SNILSBox.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.SNILSBox.setObjectName("SNILSBox")
        self.LogoImg = QtWidgets.QLabel(parent=self.widget)
        self.LogoImg.setGeometry(QtCore.QRect(126, -2, 100, 100))
        self.LogoImg.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.LogoImg.setText("")
        self.LogoImg.setPixmap(QtGui.QPixmap("resources/logo.png"))
        self.LogoImg.setScaledContents(True)
        self.LogoImg.setObjectName("LogoImg")
        RegistrationWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegistrationWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistrationWindow)

    def retranslateUi(self, RegistrationWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistrationWindow.setWindowTitle(_translate("RegistrationWindow", "Регистрация"))
        self.ConfBtn.setText(_translate("RegistrationWindow", "Политика конфиденциальности"))
        self.SignUpText.setText(_translate("RegistrationWindow", "Регистрация"))
        self.DataCheck.setText(_translate("RegistrationWindow", "         Я согласен(на) на обработку\n"
"         персональных данных"))
        self.PhoneNumberBox.setPlaceholderText(_translate("RegistrationWindow", "Номер телефона"))
        self.SignUpBtn.setText(_translate("RegistrationWindow", "Зарегистрироваться"))
        self.ConfCheck.setText(_translate("RegistrationWindow", "         Я согласен(на) с условиями\n"
"         и политикой конфиденциальности"))
        self.PasswordBox.setPlaceholderText(_translate("RegistrationWindow", "Пароль"))
        self.BirthdateBox.setPlaceholderText(_translate("RegistrationWindow", "Дата рождения (дд.мм.гггг)"))
        self.FIOBox.setPlaceholderText(_translate("RegistrationWindow", "ФИО"))
        self.SNILSBox.setPlaceholderText(_translate("RegistrationWindow", "СНИЛС"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistrationWindow = QtWidgets.QMainWindow()
    ui = Ui_RegistrationWindow()
    ui.setupUi(RegistrationWindow)
    RegistrationWindow.show()
    sys.exit(app.exec())
