# Form implementation generated from reading ui file 'EditDoctorDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditDoctorDialog(object):
    def setupUi(self, EditDoctorDialog):
        EditDoctorDialog.setObjectName("EditDoctorDialog")
        EditDoctorDialog.resize(600, 400)
        EditDoctorDialog.setStyleSheet("background-color: white;")
        self.verticalLayout = QtWidgets.QVBoxLayout(EditDoctorDialog)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=EditDoctorDialog)
        self.titleLabel.setStyleSheet("color: #1F2937;\n"
"font-size: 18px;\n"
"font-weight: bold;")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.formLayout = QtWidgets.QVBoxLayout()
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.lastNameLabel = QtWidgets.QLabel(parent=EditDoctorDialog)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.formLayout.addWidget(self.lastNameLabel)
        self.lastNameInput = QtWidgets.QLineEdit(parent=EditDoctorDialog)
        self.lastNameInput.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #D1D5DB;\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #3B82F6;\n"
"}")
        self.lastNameInput.setObjectName("lastNameInput")
        self.formLayout.addWidget(self.lastNameInput)
        self.firstNameLabel = QtWidgets.QLabel(parent=EditDoctorDialog)
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.formLayout.addWidget(self.firstNameLabel)
        self.firstNameInput = QtWidgets.QLineEdit(parent=EditDoctorDialog)
        self.firstNameInput.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #D1D5DB;\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #3B82F6;\n"
"}")
        self.firstNameInput.setObjectName("firstNameInput")
        self.formLayout.addWidget(self.firstNameInput)
        self.specialtyLabel = QtWidgets.QLabel(parent=EditDoctorDialog)
        self.specialtyLabel.setObjectName("specialtyLabel")
        self.formLayout.addWidget(self.specialtyLabel)
        self.specialtyCombo = QtWidgets.QComboBox(parent=EditDoctorDialog)
        self.specialtyCombo.setStyleSheet("")
        self.specialtyCombo.setObjectName("specialtyCombo")
        self.formLayout.addWidget(self.specialtyCombo)
        self.phoneLabel = QtWidgets.QLabel(parent=EditDoctorDialog)
        self.phoneLabel.setObjectName("phoneLabel")
        self.formLayout.addWidget(self.phoneLabel)
        self.phoneInput = QtWidgets.QLineEdit(parent=EditDoctorDialog)
        self.phoneInput.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #D1D5DB;\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #3B82F6;\n"
"}")
        self.phoneInput.setObjectName("phoneInput")
        self.formLayout.addWidget(self.phoneInput)
        self.photoPathLabel = QtWidgets.QLabel(parent=EditDoctorDialog)
        self.photoPathLabel.setObjectName("photoPathLabel")
        self.formLayout.addWidget(self.photoPathLabel)
        self.photoPathInput = QtWidgets.QLineEdit(parent=EditDoctorDialog)
        self.photoPathInput.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #D1D5DB;\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #3B82F6;\n"
"}")
        self.photoPathInput.setObjectName("photoPathInput")
        self.formLayout.addWidget(self.photoPathInput)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.saveButton = QtWidgets.QPushButton(parent=EditDoctorDialog)
        self.saveButton.setStyleSheet("QPushButton {\n"
"    background-color: #10B981;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #34D399;\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.buttonsLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(parent=EditDoctorDialog)
        self.cancelButton.setStyleSheet("QPushButton {\n"
"    background-color: #6B7280;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #9CA3AF;\n"
"}")
        self.cancelButton.setObjectName("cancelButton")
        self.buttonsLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonsLayout)

        self.retranslateUi(EditDoctorDialog)
        QtCore.QMetaObject.connectSlotsByName(EditDoctorDialog)

    def retranslateUi(self, EditDoctorDialog):
        _translate = QtCore.QCoreApplication.translate
        EditDoctorDialog.setWindowTitle(_translate("EditDoctorDialog", "Редактирование врача"))
        self.titleLabel.setText(_translate("EditDoctorDialog", "Редактирование врача"))
        self.lastNameLabel.setText(_translate("EditDoctorDialog", "Фамилия:"))
        self.lastNameInput.setPlaceholderText(_translate("EditDoctorDialog", "Фамилия"))
        self.firstNameLabel.setText(_translate("EditDoctorDialog", "Имя:"))
        self.firstNameInput.setPlaceholderText(_translate("EditDoctorDialog", "Имя"))
        self.specialtyLabel.setText(_translate("EditDoctorDialog", "Специальность:"))
        self.phoneLabel.setText(_translate("EditDoctorDialog", "Телефон:"))
        self.phoneInput.setPlaceholderText(_translate("EditDoctorDialog", "Номер телефона"))
        self.photoPathLabel.setText(_translate("EditDoctorDialog", "Путь к фото:"))
        self.photoPathInput.setPlaceholderText(_translate("EditDoctorDialog", "Путь к фотографии"))
        self.saveButton.setText(_translate("EditDoctorDialog", "Сохранить"))
        self.cancelButton.setText(_translate("EditDoctorDialog", "Отмена"))
