# Form implementation generated from reading ui file 'AddSlotWindowUi.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddSlotDialog(object):
    def setupUi(self, AddSlotDialog):
        AddSlotDialog.setObjectName("AddSlotDialog")
        AddSlotDialog.resize(500, 500)
        AddSlotDialog.setStyleSheet("QDialog {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(AddSlotDialog)
        self.verticalLayout.setContentsMargins(30, 20, 30, 20)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=AddSlotDialog)
        self.titleLabel.setStyleSheet("font-size: 20px;\n"
"font-weight: bold;\n"
"color: black;\n"
"padding: 8px;\n"
"margin-bottom: 10px;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.doctorLabel = QtWidgets.QLabel(parent=AddSlotDialog)
        self.doctorLabel.setStyleSheet("color: black;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"margin-top: 8px;\n"
"margin-bottom: 5px;")
        self.doctorLabel.setObjectName("doctorLabel")
        self.verticalLayout.addWidget(self.doctorLabel)
        self.doctorCombo = QtWidgets.QComboBox(parent=AddSlotDialog)
        self.doctorCombo.setStyleSheet("QComboBox {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 8px;\n"
"    padding: 10px 12px;\n"
"    font-size: 14px;\n"
"    color: #2a3b47;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #5fa8d3;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #3498db;\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #c5d8e6;\n"
"    background-color: #f0f6fa;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(resources/arrow-down.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 8px;\n"
"    outline: none;\n"
"    selection-background-color: #5fa8d3;\n"
"    selection-color: #ffffff;\n"
"    font-size: 14px;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 28px;\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f2f5f8;\n"
"    width: 8px;\n"
"    margin: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #b6c9d6;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #9fbcd1;\n"
"}")
        self.doctorCombo.setObjectName("doctorCombo")
        self.verticalLayout.addWidget(self.doctorCombo)
        spacerItem1 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.dateLabel = QtWidgets.QLabel(parent=AddSlotDialog)
        self.dateLabel.setStyleSheet("color: black;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"margin-top: 8px;\n"
"margin-bottom: 5px;")
        self.dateLabel.setObjectName("dateLabel")
        self.verticalLayout.addWidget(self.dateLabel)
        self.dateEdit = QtWidgets.QDateEdit(parent=AddSlotDialog)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setStyleSheet("QDateEdit {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 8px;\n"
"    padding: 10px 12px;\n"
"    font-size: 14px;\n"
"    color: #2a3b47;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}\n"
"\n"
"QDateEdit:hover {\n"
"    border: 1px solid #5fa8d3;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border: 1px solid #3498db;\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #c5d8e6;\n"
"    background-color: #f0f6fa;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    image: url(resources/arrow-down.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QDateEdit:on {\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"QCalendarWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton {\n"
"    color: #2a3b47;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QCalendarWidget QMenu {\n"
"    background-color: white;\n"
"    border: 1px solid #c5d8e6;\n"
"}\n"
"\n"
"QCalendarWidget QSpinBox {\n"
"    background-color: #f7fbff;\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
"    background-color: #f0f6fa;\n"
"    border-top-left-radius: 8px;\n"
"    border-top-right-radius: 8px;\n"
"}")
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout.addWidget(self.dateEdit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.timeLabel = QtWidgets.QLabel(parent=AddSlotDialog)
        self.timeLabel.setStyleSheet("color: black;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"margin-top: 8px;\n"
"margin-bottom: 5px;")
        self.timeLabel.setObjectName("timeLabel")
        self.verticalLayout.addWidget(self.timeLabel)
        self.timeEdit = QtWidgets.QTimeEdit(parent=AddSlotDialog)
        self.timeEdit.setStyleSheet("QTimeEdit {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 8px;\n"
"    padding: 10px 12px;\n"
"    font-size: 14px;\n"
"    color: #2a3b47;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}\n"
"\n"
"QTimeEdit:hover {\n"
"    border: 1px solid #5fa8d3;\n"
"}\n"
"\n"
"QTimeEdit:focus {\n"
"    border: 1px solid #3498db;\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"QTimeEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #c5d8e6;\n"
"    background-color: #f0f6fa;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"\n"
"QTimeEdit::down-arrow {\n"
"    image: url(resources/arrow-down.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QTimeEdit:on {\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"/* Стили для кнопок в QTimeEdit */\n"
"QTimeEdit::up-button, QTimeEdit::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: center right;\n"
"    width: 15px;\n"
"    border-left: 1px solid #c5d8e6;\n"
"    background-color: #f0f6fa;\n"
"}\n"
"\n"
"QTimeEdit::up-button {\n"
"    border-top-right-radius: 8px;\n"
"}\n"
"\n"
"QTimeEdit::down-button {\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"\n"
"QTimeEdit::up-arrow {\n"
"    image: url(resources/arrow-down.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    transform: rotate(180deg);\n"
"}\n"
"\n"
"QTimeEdit::down-arrow {\n"
"    image: url(resources/arrow-down.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}")
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout.addWidget(self.timeEdit)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(15)
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem4)
        self.saveButton = QtWidgets.QPushButton(parent=AddSlotDialog)
        self.saveButton.setMinimumSize(QtCore.QSize(140, 45))
        self.saveButton.setStyleSheet("QPushButton {\n"
"    background-color: #10B981;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-width: 140px;\n"
"    min-height: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #34D399;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0DA271;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #9CA3AF;\n"
"    color: #E5E7EB;\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(parent=AddSlotDialog)
        self.cancelButton.setMinimumSize(QtCore.QSize(120, 45))
        self.cancelButton.setStyleSheet("QPushButton {\n"
"    background-color: #F3F4F6;\n"
"    color: #374151;\n"
"    border: 1px solid #D1D5DB;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-width: 120px;\n"
"    min-height: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E5E7EB;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #D1D5DB;\n"
"}")
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(AddSlotDialog)
        QtCore.QMetaObject.connectSlotsByName(AddSlotDialog)

    def retranslateUi(self, AddSlotDialog):
        _translate = QtCore.QCoreApplication.translate
        AddSlotDialog.setWindowTitle(_translate("AddSlotDialog", "Добавить слоты записи"))
        self.titleLabel.setText(_translate("AddSlotDialog", "Добавить слоты записи"))
        self.doctorLabel.setText(_translate("AddSlotDialog", "Врач:"))
        self.dateLabel.setText(_translate("AddSlotDialog", "Дата:"))
        self.timeLabel.setText(_translate("AddSlotDialog", "Время приёма (24-часовой формат):"))
        self.timeEdit.setDisplayFormat(_translate("AddSlotDialog", "HH:mm"))
        self.saveButton.setText(_translate("AddSlotDialog", "Создать слот"))
        self.cancelButton.setText(_translate("AddSlotDialog", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddSlotDialog = QtWidgets.QDialog()
    ui = Ui_AddSlotDialog()
    ui.setupUi(AddSlotDialog)
    AddSlotDialog.show()
    sys.exit(app.exec())
