# Form implementation generated from reading ui file 'AdminPageUi.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminPage(object):
    def setupUi(self, AdminPage):
        AdminPage.setObjectName("AdminPage")
        AdminPage.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(AdminPage)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setSpacing(15)
        self.headerLayout.setObjectName("headerLayout")
        self.AdminBackBtn = QtWidgets.QPushButton(parent=AdminPage)
        self.AdminBackBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.AdminBackBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.AdminBackBtn.setStyleSheet("QPushButton {\n"
"    background-color: #F3F4F6;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"}")
        self.AdminBackBtn.setText("")
        self.AdminBackBtn.setObjectName("AdminBackBtn")
        self.headerLayout.addWidget(self.AdminBackBtn)
        self.AdminHeaderLabel = QtWidgets.QLabel(parent=AdminPage)
        self.AdminHeaderLabel.setStyleSheet("color: #1F2937;\n"
"font-size: 28px;\n"
"font-weight: bold;")
        self.AdminHeaderLabel.setObjectName("AdminHeaderLabel")
        self.headerLayout.addWidget(self.AdminHeaderLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.RefreshStatsBtn = QtWidgets.QPushButton(parent=AdminPage)
        self.RefreshStatsBtn.setMinimumSize(QtCore.QSize(120, 45))
        self.RefreshStatsBtn.setStyleSheet("QPushButton {\n"
"    background-color: #2A8BD9;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3C9AE6;\n"
"}")
        self.RefreshStatsBtn.setObjectName("RefreshStatsBtn")
        self.headerLayout.addWidget(self.RefreshStatsBtn)
        self.verticalLayout.addLayout(self.headerLayout)
        self.statsLayout = QtWidgets.QHBoxLayout()
        self.statsLayout.setSpacing(15)
        self.statsLayout.setObjectName("statsLayout")
        self.StatCard1 = QtWidgets.QWidget(parent=AdminPage)
        self.StatCard1.setMinimumSize(QtCore.QSize(0, 0))
        self.StatCard1.setStyleSheet("background-color: white;\n"
"border: 1px solid #E5E7EB;\n"
"border-radius: 10px;")
        self.StatCard1.setObjectName("StatCard1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.StatCard1)
        self.verticalLayout_2.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TotalPatientsLabel = QtWidgets.QLabel(parent=self.StatCard1)
        self.TotalPatientsLabel.setStyleSheet("color: #111827;\n"
"font-size: 32px;\n"
"font-weight: bold;")
        self.TotalPatientsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TotalPatientsLabel.setObjectName("TotalPatientsLabel")
        self.verticalLayout_2.addWidget(self.TotalPatientsLabel)
        self.label_2 = QtWidgets.QLabel(parent=self.StatCard1)
        self.label_2.setStyleSheet("color: #6B7280;\n"
"font-size: 14px;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.statsLayout.addWidget(self.StatCard1)
        self.StatCard2 = QtWidgets.QWidget(parent=AdminPage)
        self.StatCard2.setMinimumSize(QtCore.QSize(0, 0))
        self.StatCard2.setStyleSheet("background-color: white;\n"
"border: 1px solid #E5E7EB;\n"
"border-radius: 10px;")
        self.StatCard2.setObjectName("StatCard2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.StatCard2)
        self.verticalLayout_3.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.TotalDoctorsLabel = QtWidgets.QLabel(parent=self.StatCard2)
        self.TotalDoctorsLabel.setStyleSheet("color: #111827;\n"
"font-size: 32px;\n"
"font-weight: bold;")
        self.TotalDoctorsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TotalDoctorsLabel.setObjectName("TotalDoctorsLabel")
        self.verticalLayout_3.addWidget(self.TotalDoctorsLabel)
        self.label_4 = QtWidgets.QLabel(parent=self.StatCard2)
        self.label_4.setStyleSheet("color: #6B7280;\n"
"font-size: 14px;")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.statsLayout.addWidget(self.StatCard2)
        self.StatCard3 = QtWidgets.QWidget(parent=AdminPage)
        self.StatCard3.setMinimumSize(QtCore.QSize(0, 0))
        self.StatCard3.setStyleSheet("background-color: white;\n"
"border: 1px solid #E5E7EB;\n"
"border-radius: 10px;")
        self.StatCard3.setObjectName("StatCard3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.StatCard3)
        self.verticalLayout_4.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.TodayAppointmentsLabel = QtWidgets.QLabel(parent=self.StatCard3)
        self.TodayAppointmentsLabel.setStyleSheet("color: #111827;\n"
"font-size: 32px;\n"
"font-weight: bold;")
        self.TodayAppointmentsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TodayAppointmentsLabel.setObjectName("TodayAppointmentsLabel")
        self.verticalLayout_4.addWidget(self.TodayAppointmentsLabel)
        self.label_6 = QtWidgets.QLabel(parent=self.StatCard3)
        self.label_6.setStyleSheet("color: #6B7280;\n"
"font-size: 14px;")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.statsLayout.addWidget(self.StatCard3)
        self.StatCard4 = QtWidgets.QWidget(parent=AdminPage)
        self.StatCard4.setMinimumSize(QtCore.QSize(0, 0))
        self.StatCard4.setStyleSheet("background-color: white;\n"
"border: 1px solid #E5E7EB;\n"
"border-radius: 10px;")
        self.StatCard4.setObjectName("StatCard4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.StatCard4)
        self.verticalLayout_5.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.AvailableSlotsLabel = QtWidgets.QLabel(parent=self.StatCard4)
        self.AvailableSlotsLabel.setStyleSheet("color: #111827;\n"
"font-size: 32px;\n"
"font-weight: bold;")
        self.AvailableSlotsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.AvailableSlotsLabel.setObjectName("AvailableSlotsLabel")
        self.verticalLayout_5.addWidget(self.AvailableSlotsLabel)
        self.label_8 = QtWidgets.QLabel(parent=self.StatCard4)
        self.label_8.setStyleSheet("color: #6B7280;\n"
"font-size: 14px;")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.statsLayout.addWidget(self.StatCard4)
        self.verticalLayout.addLayout(self.statsLayout)
        self.actionsLayout = QtWidgets.QHBoxLayout()
        self.actionsLayout.setSpacing(10)
        self.actionsLayout.setObjectName("actionsLayout")
        self.AddDoctorBtn = QtWidgets.QPushButton(parent=AdminPage)
        self.AddDoctorBtn.setMinimumSize(QtCore.QSize(170, 50))
        self.AddDoctorBtn.setStyleSheet("QPushButton {\n"
"    background-color: #2A8BD9;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3C9AE6;\n"
"}")
        self.AddDoctorBtn.setObjectName("AddDoctorBtn")
        self.actionsLayout.addWidget(self.AddDoctorBtn)
        self.AddSlotBtn = QtWidgets.QPushButton(parent=AdminPage)
        self.AddSlotBtn.setMinimumSize(QtCore.QSize(170, 50))
        self.AddSlotBtn.setStyleSheet("QPushButton {\n"
"    background-color: #10B981;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #34D399;\n"
"}")
        self.AddSlotBtn.setObjectName("AddSlotBtn")
        self.actionsLayout.addWidget(self.AddSlotBtn)
        self.ManageSpecialtiesBtn = QtWidgets.QPushButton(parent=AdminPage)
        self.ManageSpecialtiesBtn.setMinimumSize(QtCore.QSize(150, 50))
        self.ManageSpecialtiesBtn.setStyleSheet("QPushButton {\n"
"    background-color: #8B5CF6;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A78BFA;\n"
"}")
        self.ManageSpecialtiesBtn.setObjectName("ManageSpecialtiesBtn")
        self.actionsLayout.addWidget(self.ManageSpecialtiesBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.actionsLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.actionsLayout)
        self.AdminTabWidget = QtWidgets.QTabWidget(parent=AdminPage)
        self.AdminTabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: 1px solid #E5E7EB;\n"
"    border-radius: 8px;\n"
"    background-color: white;\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #F3F4F6;\n"
"    color: #6B7280;\n"
"    padding: 15px 35px;\n"
"    margin: 2px;\n"
"    border: none;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-width: 120px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: #2A8BD9;\n"
"    color: white;\n"
"}\n"
"QTabBar::tab:hover:!selected {\n"
"    background-color: #E5E7EB;\n"
"}")
        self.AdminTabWidget.setObjectName("AdminTabWidget")
        self.DoctorsTab = QtWidgets.QWidget()
        self.DoctorsTab.setObjectName("DoctorsTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.DoctorsTab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.DoctorsTable = QtWidgets.QTableWidget(parent=self.DoctorsTab)
        self.DoctorsTable.setStyleSheet("QTableWidget {\n"
"    background-color: white;\n"
"    border: none;\n"
"    gridline-color: #F3F4F6;\n"
"    color: black;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"    border-bottom: 1px solid #F3F4F6;\n"
"    color: black;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #E1F5FE;\n"
"    color: black;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #F9FAFB;\n"
"    padding: 12px 8px;\n"
"    border: none;\n"
"    border-bottom: 2px solid #E5E7EB;\n"
"    font-weight: bold;\n"
"    color: black;\n"
"}")
        self.DoctorsTable.setObjectName("DoctorsTable")
        self.DoctorsTable.setColumnCount(0)
        self.DoctorsTable.setRowCount(0)
        self.verticalLayout_6.addWidget(self.DoctorsTable)
        self.AdminTabWidget.addTab(self.DoctorsTab, "")
        self.AppointmentsTab = QtWidgets.QWidget()
        self.AppointmentsTab.setObjectName("AppointmentsTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.AppointmentsTab)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.AppointmentsTable = QtWidgets.QTableWidget(parent=self.AppointmentsTab)
        self.AppointmentsTable.setStyleSheet("QTableWidget {\n"
"    background-color: white;\n"
"    border: none;\n"
"    gridline-color: #F3F4F6;\n"
"    color: black;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"    border-bottom: 1px solid #F3F4F6;\n"
"    color: black;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #E1F5FE;\n"
"    color: black;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #F9FAFB;\n"
"    padding: 12px 8px;\n"
"    border: none;\n"
"    border-bottom: 2px solid #E5E7EB;\n"
"    font-weight: bold;\n"
"    color: black;\n"
"}")
        self.AppointmentsTable.setObjectName("AppointmentsTable")
        self.AppointmentsTable.setColumnCount(0)
        self.AppointmentsTable.setRowCount(0)
        self.verticalLayout_7.addWidget(self.AppointmentsTable)
        self.AdminTabWidget.addTab(self.AppointmentsTab, "")
        self.ActivityTab = QtWidgets.QWidget()
        self.ActivityTab.setObjectName("ActivityTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ActivityTab)
        self.verticalLayout_8.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(parent=self.ActivityTab)
        self.label.setStyleSheet("color: #374151;\n"
"font-size: 16px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.RecentActivityText = QtWidgets.QTextEdit(parent=self.ActivityTab)
        self.RecentActivityText.setStyleSheet("background-color: white;\n"
"border: 1px solid #E5E7EB;\n"
"border-radius: 8px;\n"
"padding: 12px;\n"
"color: black;")
        self.RecentActivityText.setReadOnly(True)
        self.RecentActivityText.setObjectName("RecentActivityText")
        self.verticalLayout_8.addWidget(self.RecentActivityText)
        self.AdminTabWidget.addTab(self.ActivityTab, "")
        self.verticalLayout.addWidget(self.AdminTabWidget)

        self.retranslateUi(AdminPage)
        self.AdminTabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(AdminPage)

    def retranslateUi(self, AdminPage):
        _translate = QtCore.QCoreApplication.translate
        AdminPage.setWindowTitle(_translate("AdminPage", "Панель администратора"))
        self.AdminHeaderLabel.setText(_translate("AdminPage", "Панель администратора"))
        self.RefreshStatsBtn.setText(_translate("AdminPage", "Обновить"))
        self.TotalPatientsLabel.setText(_translate("AdminPage", "0"))
        self.label_2.setText(_translate("AdminPage", "Пациентов"))
        self.TotalDoctorsLabel.setText(_translate("AdminPage", "0"))
        self.label_4.setText(_translate("AdminPage", "Врачей"))
        self.TodayAppointmentsLabel.setText(_translate("AdminPage", "0"))
        self.label_6.setText(_translate("AdminPage", "Записей сегодня"))
        self.AvailableSlotsLabel.setText(_translate("AdminPage", "0"))
        self.label_8.setText(_translate("AdminPage", "Свободных слотов"))
        self.AddDoctorBtn.setText(_translate("AdminPage", "+ Добавить врача"))
        self.AddSlotBtn.setText(_translate("AdminPage", "+ Добавить слоты"))
        self.ManageSpecialtiesBtn.setText(_translate("AdminPage", "Специальности"))
        self.AdminTabWidget.setTabText(self.AdminTabWidget.indexOf(self.DoctorsTab), _translate("AdminPage", "Врачи"))
        self.AdminTabWidget.setTabText(self.AdminTabWidget.indexOf(self.AppointmentsTab), _translate("AdminPage", "Записи"))
        self.label.setText(_translate("AdminPage", "Последняя активность"))
        self.AdminTabWidget.setTabText(self.AdminTabWidget.indexOf(self.ActivityTab), _translate("AdminPage", "Активность"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminPage = QtWidgets.QWidget()
    ui = Ui_AdminPage()
    ui.setupUi(AdminPage)
    AdminPage.show()
    sys.exit(app.exec())
