# Form implementation generated from reading ui file 'AuthorizationWindowUi.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthorizationWindowUi(object):
    def setupUi(self, AuthorizationWindowUi):
        AuthorizationWindowUi.setObjectName("AuthorizationWindowUi")
        AuthorizationWindowUi.resize(800, 640)
        AuthorizationWindowUi.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"QLineEdit {\n"
"    border: 2px solid #E9E9E9;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=AuthorizationWindowUi)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.BackgroundImg = QtWidgets.QLabel(parent=self.centralwidget)
        self.BackgroundImg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.BackgroundImg.setText("")
        self.BackgroundImg.setScaledContents(True)
        self.BackgroundImg.setObjectName("BackgroundImg")
        self.gridLayout.addWidget(self.BackgroundImg, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(361, 591))
        self.widget.setMaximumSize(QtCore.QSize(361, 591))
        self.widget.setStyleSheet("background-color: rgba(255, 255, 255, 135);\n"
"border-radius: 20px;")
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.LogInBtn = QtWidgets.QPushButton(parent=self.widget)
        self.LogInBtn.setGeometry(QtCore.QRect(80, 370, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.LogInBtn.setFont(font)
        self.LogInBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.LogInBtn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #2883CD;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: #2A8BD9;\n"
"    font-weight: bold;\n"
"}")
        self.LogInBtn.setObjectName("LogInBtn")
        self.SignUpBtn = QtWidgets.QPushButton(parent=self.widget)
        self.SignUpBtn.setGeometry(QtCore.QRect(155, 550, 134, 18))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(14)
        font.setUnderline(True)
        self.SignUpBtn.setFont(font)
        self.SignUpBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.SignUpBtn.setStyleSheet("color: rgb(14, 109, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.SignUpBtn.setObjectName("SignUpBtn")
        self.Line1 = QtWidgets.QFrame(parent=self.widget)
        self.Line1.setGeometry(QtCore.QRect(25, 470, 118, 2))
        self.Line1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Line1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.Line1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.Line1.setObjectName("Line1")
        self.LoginBox = QtWidgets.QLineEdit(parent=self.widget)
        self.LoginBox.setGeometry(QtCore.QRect(25, 230, 308, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LoginBox.setFont(font)
        self.LoginBox.setToolTipDuration(-1)
        self.LoginBox.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid #E9E9E9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.LoginBox.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.LoginBox.setPlaceholderText("")
        self.LoginBox.setObjectName("LoginBox")
        self.HintText = QtWidgets.QLabel(parent=self.widget)
        self.HintText.setGeometry(QtCore.QRect(34, 170, 290, 51))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.HintText.setFont(font)
        self.HintText.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.HintText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.HintText.setWordWrap(True)
        self.HintText.setObjectName("HintText")
        self.LineText = QtWidgets.QLabel(parent=self.widget)
        self.LineText.setGeometry(QtCore.QRect(164, 461, 32, 14))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(18)
        self.LineText.setFont(font)
        self.LineText.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.LineText.setObjectName("LineText")
        self.NoAccText = QtWidgets.QLabel(parent=self.widget)
        self.NoAccText.setGeometry(QtCore.QRect(74, 550, 94, 18))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(14)
        self.NoAccText.setFont(font)
        self.NoAccText.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.NoAccText.setObjectName("NoAccText")
        self.NameMCText = QtWidgets.QLabel(parent=self.widget)
        self.NameMCText.setGeometry(QtCore.QRect(135, 26, 181, 61))
        font = QtGui.QFont()
        font.setFamily(".Lucida Grande UI")
        font.setPointSize(25)
        font.setKerning(True)
        self.NameMCText.setFont(font)
        self.NameMCText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.NameMCText.setWordWrap(True)
        self.NameMCText.setObjectName("NameMCText")
        self.ForgotPassBtn = QtWidgets.QPushButton(parent=self.widget)
        self.ForgotPassBtn.setGeometry(QtCore.QRect(112, 425, 134, 24))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(16)
        font.setUnderline(True)
        self.ForgotPassBtn.setFont(font)
        self.ForgotPassBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ForgotPassBtn.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.ForgotPassBtn.setObjectName("ForgotPassBtn")
        self.LogoImg = QtWidgets.QLabel(parent=self.widget)
        self.LogoImg.setGeometry(QtCore.QRect(35, 10, 100, 100))
        self.LogoImg.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.LogoImg.setText("")
        self.LogoImg.setPixmap(QtGui.QPixmap("resources/logo.png"))
        self.LogoImg.setScaledContents(True)
        self.LogoImg.setObjectName("LogoImg")
        self.LogInGosBtn = QtWidgets.QPushButton(parent=self.widget)
        self.LogInGosBtn.setGeometry(QtCore.QRect(25, 490, 308, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LogInGosBtn.setFont(font)
        self.LogInGosBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.LogInGosBtn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid #E9E9E9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-weight: bold;\n"
"}")
        self.LogInGosBtn.setIconSize(QtCore.QSize(30, 30))
        self.LogInGosBtn.setAutoRepeatDelay(300)
        self.LogInGosBtn.setAutoRepeatInterval(100)
        self.LogInGosBtn.setObjectName("LogInGosBtn")
        self.WelcomeText = QtWidgets.QLabel(parent=self.widget)
        self.WelcomeText.setGeometry(QtCore.QRect(70, 100, 240, 61))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.WelcomeText.setFont(font)
        self.WelcomeText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.WelcomeText.setObjectName("WelcomeText")
        self.PasswordBox = QtWidgets.QLineEdit(parent=self.widget)
        self.PasswordBox.setGeometry(QtCore.QRect(25, 300, 308, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PasswordBox.setFont(font)
        self.PasswordBox.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid #E9E9E9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.PasswordBox.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.PasswordBox.setObjectName("PasswordBox")
        self.Line2 = QtWidgets.QFrame(parent=self.widget)
        self.Line2.setGeometry(QtCore.QRect(216, 470, 118, 2))
        self.Line2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Line2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.Line2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.Line2.setObjectName("Line2")
        AuthorizationWindowUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(AuthorizationWindowUi)
        QtCore.QMetaObject.connectSlotsByName(AuthorizationWindowUi)

    def retranslateUi(self, AuthorizationWindowUi):
        _translate = QtCore.QCoreApplication.translate
        AuthorizationWindowUi.setWindowTitle(_translate("AuthorizationWindowUi", "Авторизация"))
        self.LogInBtn.setText(_translate("AuthorizationWindowUi", "Войти"))
        self.SignUpBtn.setText(_translate("AuthorizationWindowUi", "Зарегистрироваться"))
        self.HintText.setWhatsThis(_translate("AuthorizationWindowUi", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.HintText.setText(_translate("AuthorizationWindowUi", "Войдите, чтобы управлять записями и услугами"))
        self.LineText.setText(_translate("AuthorizationWindowUi", "или"))
        self.NoAccText.setText(_translate("AuthorizationWindowUi", "Нет аккаунта?"))
        self.NameMCText.setText(_translate("AuthorizationWindowUi", "Медицинский центр"))
        self.ForgotPassBtn.setText(_translate("AuthorizationWindowUi", "Забыли пароль?"))
        self.LogInGosBtn.setText(_translate("AuthorizationWindowUi", "Войти через Госуслуги"))
        self.WelcomeText.setText(_translate("AuthorizationWindowUi", "Добро пожаловать!"))
        self.PasswordBox.setPlaceholderText(_translate("AuthorizationWindowUi", "Пароль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AuthorizationWindowUi = QtWidgets.QMainWindow()
    ui = Ui_AuthorizationWindowUi()
    ui.setupUi(AuthorizationWindowUi)
    AuthorizationWindowUi.show()
    sys.exit(app.exec())
