# Form implementation generated from reading ui file 'AddDoctorWindowUi.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddDoctorDialog(object):
    def setupUi(self, AddDoctorDialog):
        AddDoctorDialog.setObjectName("AddDoctorDialog")
        AddDoctorDialog.resize(500, 600)
        AddDoctorDialog.setStyleSheet("QDialog {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(AddDoctorDialog)
        self.verticalLayout.setContentsMargins(30, 20, 30, 20)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=AddDoctorDialog)
        self.titleLabel.setStyleSheet("font-size: 20px;\n"
"font-weight: bold;\n"
"color: black;\n"
"padding: 8px;\n"
"margin-bottom: 10px;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lastNameLabel = QtWidgets.QLabel(parent=AddDoctorDialog)
        self.lastNameLabel.setStyleSheet("color: black;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"margin-top: 8px;\n"
"margin-bottom: 5px;")
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.verticalLayout.addWidget(self.lastNameLabel)
        self.lastNameInput = QtWidgets.QLineEdit(parent=AddDoctorDialog)
        self.lastNameInput.setStyleSheet("QLineEdit {\n"
"    padding: 10px 12px;\n"
"    border: 1px solid #E5E7EB;\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid #2A8BD9;\n"
"    background-color: #F7FBFF;\n"
"}")
        self.lastNameInput.setObjectName("lastNameInput")
        self.verticalLayout.addWidget(self.lastNameInput)
        spacerItem1 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.firstNameLabel = QtWidgets.QLabel(parent=AddDoctorDialog)
        self.firstNameLabel.setStyleSheet("color: black;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"margin-top: 8px;\n"
"margin-bottom: 5px;")
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.verticalLayout.addWidget(self.firstNameLabel)
        self.firstNameInput = QtWidgets.QLineEdit(parent=AddDoctorDialog)
        self.firstNameInput.setStyleSheet("QLineEdit {\n"
"    padding: 10px 12px;\n"
"    border: 1px solid #E5E7EB;\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid #2A8BD9;\n"
"    background-color: #F7FBFF;\n"
"}")
        self.firstNameInput.setObjectName("firstNameInput")
        self.verticalLayout.addWidget(self.firstNameInput)
        spacerItem2 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.specialtyLabel = QtWidgets.QLabel(parent=AddDoctorDialog)
        self.specialtyLabel.setStyleSheet("color: black;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"margin-top: 8px;\n"
"margin-bottom: 5px;")
        self.specialtyLabel.setObjectName("specialtyLabel")
        self.verticalLayout.addWidget(self.specialtyLabel)
        self.specialtyCombo = QtWidgets.QComboBox(parent=AddDoctorDialog)
        self.specialtyCombo.setStyleSheet("QComboBox {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 8px;\n"
"    padding: 10px 12px;\n"
"    font-size: 14px;\n"
"    color: #2a3b47;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #5fa8d3;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #3498db;\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #c5d8e6;\n"
"    background-color: #f0f6fa;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(resources/arrow-down.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 8px;\n"
"    outline: none;\n"
"    selection-background-color: #5fa8d3;\n"
"    selection-color: #ffffff;\n"
"    font-size: 14px;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 28px;\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f2f5f8;\n"
"    width: 8px;\n"
"    margin: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #b6c9d6;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #9fbcd1;\n"
"}")
        self.specialtyCombo.setObjectName("specialtyCombo")
        self.verticalLayout.addWidget(self.specialtyCombo)
        spacerItem3 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.photoLabel = QtWidgets.QLabel(parent=AddDoctorDialog)
        self.photoLabel.setStyleSheet("color: black;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"margin-top: 8px;\n"
"margin-bottom: 5px;")
        self.photoLabel.setObjectName("photoLabel")
        self.verticalLayout.addWidget(self.photoLabel)
        self.photoPathInput = QtWidgets.QLineEdit(parent=AddDoctorDialog)
        self.photoPathInput.setStyleSheet("QLineEdit {\n"
"    padding: 10px 12px;\n"
"    border: 1px solid #E5E7EB;\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid #2A8BD9;\n"
"    background-color: #F7FBFF;\n"
"}")
        self.photoPathInput.setObjectName("photoPathInput")
        self.verticalLayout.addWidget(self.photoPathInput)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(15)
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem5)
        self.saveButton = QtWidgets.QPushButton(parent=AddDoctorDialog)
        self.saveButton.setMinimumSize(QtCore.QSize(120, 45))
        self.saveButton.setStyleSheet("QPushButton {\n"
"    background-color: #2A8BD9;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-width: 120px;\n"
"    min-height: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3C9AE6;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1E6FBF;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #9CA3AF;\n"
"    color: #E5E7EB;\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(parent=AddDoctorDialog)
        self.cancelButton.setMinimumSize(QtCore.QSize(120, 45))
        self.cancelButton.setStyleSheet("QPushButton {\n"
"    background-color: #F3F4F6;\n"
"    color: #374151;\n"
"    border: 1px solid #D1D5DB;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-width: 120px;\n"
"    min-height: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E5E7EB;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #D1D5DB;\n"
"}")
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(AddDoctorDialog)
        QtCore.QMetaObject.connectSlotsByName(AddDoctorDialog)

    def retranslateUi(self, AddDoctorDialog):
        _translate = QtCore.QCoreApplication.translate
        AddDoctorDialog.setWindowTitle(_translate("AddDoctorDialog", "Добавить врача"))
        self.titleLabel.setText(_translate("AddDoctorDialog", "Добавить врача"))
        self.lastNameLabel.setText(_translate("AddDoctorDialog", "Фамилия:"))
        self.lastNameInput.setPlaceholderText(_translate("AddDoctorDialog", "Введите фамилию"))
        self.firstNameLabel.setText(_translate("AddDoctorDialog", "Имя:"))
        self.firstNameInput.setPlaceholderText(_translate("AddDoctorDialog", "Введите имя"))
        self.specialtyLabel.setText(_translate("AddDoctorDialog", "Специальность:"))
        self.photoLabel.setText(_translate("AddDoctorDialog", "Фото:"))
        self.photoPathInput.setPlaceholderText(_translate("AddDoctorDialog", "Путь к файлу фото (необязательно)"))
        self.saveButton.setText(_translate("AddDoctorDialog", "Сохранить"))
        self.cancelButton.setText(_translate("AddDoctorDialog", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddDoctorDialog = QtWidgets.QDialog()
    ui = Ui_AddDoctorDialog()
    ui.setupUi(AddDoctorDialog)
    AddDoctorDialog.show()
    sys.exit(app.exec())
