# Form implementation generated from reading ui file 'DoctorWindowUi.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DoctorWindow(object):
    def setupUi(self, DoctorWindow):
        DoctorWindow.setObjectName("DoctorWindow")
        DoctorWindow.resize(800, 640)
        DoctorWindow.setStyleSheet("background-color: #F8F9FB;")
        self.centralwidget = QtWidgets.QWidget(parent=DoctorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.BackgroundImg = QtWidgets.QLabel(parent=self.centralwidget)
        self.BackgroundImg.setStyleSheet("background-color: #F8F9FB;")
        self.BackgroundImg.setText("")
        self.BackgroundImg.setScaledContents(True)
        self.BackgroundImg.setObjectName("BackgroundImg")
        self.gridLayout.addWidget(self.BackgroundImg, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(800, 640))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setStyleSheet("background-color: #F8F9FB;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.doctorInfoLayout = QtWidgets.QVBoxLayout()
        self.doctorInfoLayout.setSpacing(5)
        self.doctorInfoLayout.setObjectName("doctorInfoLayout")
        self.doctorNameLabel = QtWidgets.QLabel(parent=self.widget)
        self.doctorNameLabel.setStyleSheet("color: #1F2937; font-size: 24px; font-weight: bold;")
        self.doctorNameLabel.setObjectName("doctorNameLabel")
        self.doctorInfoLayout.addWidget(self.doctorNameLabel)
        self.doctorSpecLabel = QtWidgets.QLabel(parent=self.widget)
        self.doctorSpecLabel.setStyleSheet("color: #6B7280; font-size: 16px;")
        self.doctorSpecLabel.setObjectName("doctorSpecLabel")
        self.doctorInfoLayout.addWidget(self.doctorSpecLabel)
        self.headerLayout.addLayout(self.doctorInfoLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.refreshBtn = QtWidgets.QPushButton(parent=self.widget)
        self.refreshBtn.setStyleSheet("QPushButton {\n"
"    background-color: #2A8BD9;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3C9AE6;\n"
"}")
        self.refreshBtn.setObjectName("refreshBtn")
        self.headerLayout.addWidget(self.refreshBtn)
        self.verticalLayout.addLayout(self.headerLayout)
        self.statsLayout = QtWidgets.QHBoxLayout()
        self.statsLayout.setSpacing(15)
        self.statsLayout.setObjectName("statsLayout")
        self.todayAppointmentsCard = QtWidgets.QWidget(parent=self.widget)
        self.todayAppointmentsCard.setMinimumSize(QtCore.QSize(0, 0))
        self.todayAppointmentsCard.setStyleSheet("background-color: white; border: 1px solid #E5E7EB; border-radius: 10px;")
        self.todayAppointmentsCard.setObjectName("todayAppointmentsCard")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.todayAppointmentsCard)
        self.verticalLayout_2.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.todayAppointmentsValue = QtWidgets.QLabel(parent=self.todayAppointmentsCard)
        self.todayAppointmentsValue.setStyleSheet("color: #111827; font-size: 32px; font-weight: bold;")
        self.todayAppointmentsValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.todayAppointmentsValue.setObjectName("todayAppointmentsValue")
        self.verticalLayout_2.addWidget(self.todayAppointmentsValue)
        self.todayAppointmentsLabel = QtWidgets.QLabel(parent=self.todayAppointmentsCard)
        self.todayAppointmentsLabel.setStyleSheet("color: #6B7280; font-size: 14px;")
        self.todayAppointmentsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.todayAppointmentsLabel.setObjectName("todayAppointmentsLabel")
        self.verticalLayout_2.addWidget(self.todayAppointmentsLabel)
        self.statsLayout.addWidget(self.todayAppointmentsCard)
        self.totalAppointmentsCard = QtWidgets.QWidget(parent=self.widget)
        self.totalAppointmentsCard.setMinimumSize(QtCore.QSize(0, 0))
        self.totalAppointmentsCard.setStyleSheet("background-color: white; border: 1px solid #E5E7EB; border-radius: 10px;")
        self.totalAppointmentsCard.setObjectName("totalAppointmentsCard")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.totalAppointmentsCard)
        self.verticalLayout_3.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.totalAppointmentsValue = QtWidgets.QLabel(parent=self.totalAppointmentsCard)
        self.totalAppointmentsValue.setStyleSheet("color: #111827; font-size: 32px; font-weight: bold;")
        self.totalAppointmentsValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.totalAppointmentsValue.setObjectName("totalAppointmentsValue")
        self.verticalLayout_3.addWidget(self.totalAppointmentsValue)
        self.totalAppointmentsLabel = QtWidgets.QLabel(parent=self.totalAppointmentsCard)
        self.totalAppointmentsLabel.setStyleSheet("color: #6B7280; font-size: 14px;")
        self.totalAppointmentsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.totalAppointmentsLabel.setObjectName("totalAppointmentsLabel")
        self.verticalLayout_3.addWidget(self.totalAppointmentsLabel)
        self.statsLayout.addWidget(self.totalAppointmentsCard)
        self.completedCard = QtWidgets.QWidget(parent=self.widget)
        self.completedCard.setMinimumSize(QtCore.QSize(0, 0))
        self.completedCard.setStyleSheet("background-color: white; border: 1px solid #E5E7EB; border-radius: 10px;")
        self.completedCard.setObjectName("completedCard")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.completedCard)
        self.verticalLayout_4.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.completedValue = QtWidgets.QLabel(parent=self.completedCard)
        self.completedValue.setStyleSheet("color: #111827; font-size: 32px; font-weight: bold;")
        self.completedValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.completedValue.setObjectName("completedValue")
        self.verticalLayout_4.addWidget(self.completedValue)
        self.completedLabel = QtWidgets.QLabel(parent=self.completedCard)
        self.completedLabel.setStyleSheet("color: #6B7280; font-size: 14px;")
        self.completedLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.completedLabel.setObjectName("completedLabel")
        self.verticalLayout_4.addWidget(self.completedLabel)
        self.statsLayout.addWidget(self.completedCard)
        self.cancelledCard = QtWidgets.QWidget(parent=self.widget)
        self.cancelledCard.setMinimumSize(QtCore.QSize(0, 0))
        self.cancelledCard.setStyleSheet("background-color: white; border: 1px solid #E5E7EB; border-radius: 10px;")
        self.cancelledCard.setObjectName("cancelledCard")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.cancelledCard)
        self.verticalLayout_5.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cancelledValue = QtWidgets.QLabel(parent=self.cancelledCard)
        self.cancelledValue.setStyleSheet("color: #111827; font-size: 32px; font-weight: bold;")
        self.cancelledValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cancelledValue.setObjectName("cancelledValue")
        self.verticalLayout_5.addWidget(self.cancelledValue)
        self.cancelledLabel = QtWidgets.QLabel(parent=self.cancelledCard)
        self.cancelledLabel.setStyleSheet("color: #6B7280; font-size: 14px;")
        self.cancelledLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cancelledLabel.setObjectName("cancelledLabel")
        self.verticalLayout_5.addWidget(self.cancelledLabel)
        self.statsLayout.addWidget(self.cancelledCard)
        self.verticalLayout.addLayout(self.statsLayout)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.widget)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: 1px solid #E5E7EB;\n"
"    border-radius: 8px;\n"
"    background-color: white;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #F3F4F6;\n"
"    color: #6B7280;\n"
"    padding: 12px 24px;\n"
"    margin: 2px;\n"
"    border: none;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: #2A8BD9;\n"
"    color: white;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.todayTab = QtWidgets.QWidget()
        self.todayTab.setObjectName("todayTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.todayTab)
        self.verticalLayout_6.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.todayLabel = QtWidgets.QLabel(parent=self.todayTab)
        self.todayLabel.setStyleSheet("color: #374151; font-size: 18px; font-weight: bold;")
        self.todayLabel.setObjectName("todayLabel")
        self.verticalLayout_6.addWidget(self.todayLabel)
        self.todayTable = QtWidgets.QTableWidget(parent=self.todayTab)
        self.todayTable.setStyleSheet("QTableWidget {\n"
"    background-color: white;\n"
"    color: black;\n"
"    gridline-color: #F3F4F6;\n"
"    font-size: 14px;\n"
"}\n"
"QTableWidget::item {\n"
"    color: black;\n"
"    border-bottom: 1px solid #F3F4F6;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #F9FAFB;\n"
"    color: black;\n"
"    padding: 15px 10px;\n"
"    border: none;\n"
"    border-bottom: 2px solid #E5E7EB;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}")
        self.todayTable.setRowCount(0)
        self.todayTable.setColumnCount(6)
        self.todayTable.setObjectName("todayTable")
        item = QtWidgets.QTableWidgetItem()
        self.todayTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTable.setHorizontalHeaderItem(5, item)
        self.todayTable.horizontalHeader().setVisible(True)
        self.todayTable.horizontalHeader().setHighlightSections(True)
        self.todayTable.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.todayTable.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.todayTable.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.todayTable.horizontalHeader().setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.todayTable.horizontalHeader().setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.todayTable.horizontalHeader().setSectionResizeMode(5, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.verticalLayout_6.addWidget(self.todayTable)
        self.tabWidget.addTab(self.todayTab, "")
        self.allTab = QtWidgets.QWidget()
        self.allTab.setObjectName("allTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.allTab)
        self.verticalLayout_7.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.allLabel = QtWidgets.QLabel(parent=self.allTab)
        self.allLabel.setStyleSheet("color: #374151; font-size: 18px; font-weight: bold;")
        self.allLabel.setObjectName("allLabel")
        self.verticalLayout_7.addWidget(self.allLabel)
        self.allTable = QtWidgets.QTableWidget(parent=self.allTab)
        self.allTable.setStyleSheet("QTableWidget {\n"
"    background-color: white;\n"
"    color: black;\n"
"    gridline-color: #F3F4F6;\n"
"    font-size: 14px;\n"
"}\n"
"QTableWidget::item {\n"
"    color: black;\n"
"    border-bottom: 1px solid #F3F4F6;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #F9FAFB;\n"
"    color: black;\n"
"    padding: 15px 10px;\n"
"    border: none;\n"
"    border-bottom: 2px solid #E5E7EB;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}")
        self.allTable.setRowCount(0)
        self.allTable.setColumnCount(7)
        self.allTable.setObjectName("allTable")
        item = QtWidgets.QTableWidgetItem()
        self.allTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.allTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.allTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.allTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.allTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.allTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.allTable.setHorizontalHeaderItem(6, item)
        self.allTable.horizontalHeader().setVisible(True)
        self.allTable.horizontalHeader().setHighlightSections(True)
        self.allTable.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.allTable.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.allTable.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.allTable.horizontalHeader().setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.allTable.horizontalHeader().setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.allTable.horizontalHeader().setSectionResizeMode(5, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.allTable.horizontalHeader().setSectionResizeMode(6, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.verticalLayout_7.addWidget(self.allTable)
        self.tabWidget.addTab(self.allTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        DoctorWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(DoctorWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DoctorWindow)

    def retranslateUi(self, DoctorWindow):
        _translate = QtCore.QCoreApplication.translate
        DoctorWindow.setWindowTitle(_translate("DoctorWindow", "Панель врача"))
        self.doctorNameLabel.setText(_translate("DoctorWindow", "Добро пожаловать, Доктор!"))
        self.doctorSpecLabel.setText(_translate("DoctorWindow", "Специальность: "))
        self.refreshBtn.setText(_translate("DoctorWindow", "Обновить"))
        self.todayAppointmentsValue.setText(_translate("DoctorWindow", "0"))
        self.todayAppointmentsLabel.setText(_translate("DoctorWindow", "Записей на сегодня"))
        self.totalAppointmentsValue.setText(_translate("DoctorWindow", "0"))
        self.totalAppointmentsLabel.setText(_translate("DoctorWindow", "Всего записей"))
        self.completedValue.setText(_translate("DoctorWindow", "0"))
        self.completedLabel.setText(_translate("DoctorWindow", "Завершено"))
        self.cancelledValue.setText(_translate("DoctorWindow", "0"))
        self.cancelledLabel.setText(_translate("DoctorWindow", "Отменено"))
        self.todayLabel.setText(_translate("DoctorWindow", "Записи на сегодня"))
        item = self.todayTable.horizontalHeaderItem(0)
        item.setText(_translate("DoctorWindow", "Пациент"))
        item = self.todayTable.horizontalHeaderItem(1)
        item.setText(_translate("DoctorWindow", "Дата рождения"))
        item = self.todayTable.horizontalHeaderItem(2)
        item.setText(_translate("DoctorWindow", "СНИЛС"))
        item = self.todayTable.horizontalHeaderItem(3)
        item.setText(_translate("DoctorWindow", "Телефон"))
        item = self.todayTable.horizontalHeaderItem(4)
        item.setText(_translate("DoctorWindow", "Время"))
        item = self.todayTable.horizontalHeaderItem(5)
        item.setText(_translate("DoctorWindow", "Действия"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.todayTab), _translate("DoctorWindow", "На сегодня"))
        self.allLabel.setText(_translate("DoctorWindow", "Все записи"))
        item = self.allTable.horizontalHeaderItem(0)
        item.setText(_translate("DoctorWindow", "Пациент"))
        item = self.allTable.horizontalHeaderItem(1)
        item.setText(_translate("DoctorWindow", "Дата рождения"))
        item = self.allTable.horizontalHeaderItem(2)
        item.setText(_translate("DoctorWindow", "СНИЛС"))
        item = self.allTable.horizontalHeaderItem(3)
        item.setText(_translate("DoctorWindow", "Телефон"))
        item = self.allTable.horizontalHeaderItem(4)
        item.setText(_translate("DoctorWindow", "Дата"))
        item = self.allTable.horizontalHeaderItem(5)
        item.setText(_translate("DoctorWindow", "Время"))
        item = self.allTable.horizontalHeaderItem(6)
        item.setText(_translate("DoctorWindow", "Действия"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.allTab), _translate("DoctorWindow", "Все записи"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DoctorWindow = QtWidgets.QMainWindow()
    ui = Ui_DoctorWindow()
    ui.setupUi(DoctorWindow)
    DoctorWindow.show()
    sys.exit(app.exec())
