# Form implementation generated from reading ui file 'AllHomePagesUi.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HomeWindow(object):
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(800, 640)
        HomeWindow.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=HomeWindow)
        self.centralwidget.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.BackgroundImg = QtWidgets.QLabel(parent=self.centralwidget)
        self.BackgroundImg.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.BackgroundImg.setText("")
        self.BackgroundImg.setScaledContents(True)
        self.BackgroundImg.setObjectName("BackgroundImg")
        self.gridLayout.addWidget(self.BackgroundImg, 0, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_6.setMinimumSize(QtCore.QSize(780, 620))
        self.widget_6.setMaximumSize(QtCore.QSize(780, 620))
        self.widget_6.setStyleSheet("background-color: rgba(255, 255, 255, 70);\n"
"border-radius: 20px;")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout.addWidget(self.widget_6, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_6)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 780, 620))
        self.stackedWidget.setStyleSheet("backgorund-color: rgba(0,0,0,0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.HomePage = QtWidgets.QWidget()
        self.HomePage.setObjectName("HomePage")
        self.LogoImg = QtWidgets.QLabel(parent=self.HomePage)
        self.LogoImg.setGeometry(QtCore.QRect(50, 26, 121, 121))
        self.LogoImg.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.LogoImg.setText("")
        self.LogoImg.setScaledContents(True)
        self.LogoImg.setObjectName("LogoImg")
        self.MyRecordsBtn = QtWidgets.QPushButton(parent=self.HomePage)
        self.MyRecordsBtn.setGeometry(QtCore.QRect(50, 220, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Lao MN")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.MyRecordsBtn.setFont(font)
        self.MyRecordsBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.MyRecordsBtn.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #2A8BD9;\n"
"border-radius: 10px;\n"
"border: 1px solid #B4B4B4;\n"
"font-weight: bold;")
        self.MyRecordsBtn.setObjectName("MyRecordsBtn")
        self.MyAccountBtn = QtWidgets.QPushButton(parent=self.HomePage)
        self.MyAccountBtn.setGeometry(QtCore.QRect(50, 150, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Lao MN")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.MyAccountBtn.setFont(font)
        self.MyAccountBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.MyAccountBtn.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #2A8BD9;\n"
"border-radius: 10px;\n"
"border: 1px solid #B4B4B4;\n"
"font-weight: bold;")
        self.MyAccountBtn.setObjectName("MyAccountBtn")
        self.GlavVrachWidget = QtWidgets.QWidget(parent=self.HomePage)
        self.GlavVrachWidget.setGeometry(QtCore.QRect(480, 50, 271, 541))
        self.GlavVrachWidget.setStyleSheet("border: 1px solid #B4B4B4;\n"
"border-radius: 15px;")
        self.GlavVrachWidget.setObjectName("GlavVrachWidget")
        self.GlavVrachText = QtWidgets.QLabel(parent=self.GlavVrachWidget)
        self.GlavVrachText.setGeometry(QtCore.QRect(20, 10, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.GlavVrachText.setFont(font)
        self.GlavVrachText.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.GlavVrachText.setObjectName("GlavVrachText")
        self.GlavVrachImg = QtWidgets.QLabel(parent=self.GlavVrachWidget)
        self.GlavVrachImg.setGeometry(QtCore.QRect(20, 50, 231, 171))
        self.GlavVrachImg.setStyleSheet("border: 0px solid black;\n"
"border-radius: 0px;")
        self.GlavVrachImg.setText("")
        self.GlavVrachImg.setObjectName("GlavVrachImg")
        self.GlavVrachFIOText = QtWidgets.QLabel(parent=self.GlavVrachWidget)
        self.GlavVrachFIOText.setGeometry(QtCore.QRect(20, 230, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.GlavVrachFIOText.setFont(font)
        self.GlavVrachFIOText.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font-weight: bold;")
        self.GlavVrachFIOText.setObjectName("GlavVrachFIOText")
        self.GlavVrachSpecText = QtWidgets.QLabel(parent=self.GlavVrachWidget)
        self.GlavVrachSpecText.setGeometry(QtCore.QRect(20, 260, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.GlavVrachSpecText.setFont(font)
        self.GlavVrachSpecText.setStyleSheet("border: 0px;\n"
"color: #4A4A4A;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.GlavVrachSpecText.setObjectName("GlavVrachSpecText")
        self.Line = QtWidgets.QFrame(parent=self.GlavVrachWidget)
        self.Line.setGeometry(QtCore.QRect(20, 296, 231, 2))
        self.Line.setStyleSheet("border-radius: 10px;")
        self.Line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.Line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.Line.setObjectName("Line")
        self.Line2 = QtWidgets.QFrame(parent=self.GlavVrachWidget)
        self.Line2.setGeometry(QtCore.QRect(20, 380, 231, 2))
        self.Line2.setStyleSheet("border-radius: 10px;")
        self.Line2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.Line2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.Line2.setObjectName("Line2")
        self.MapsBtn = QtWidgets.QPushButton(parent=self.GlavVrachWidget)
        self.MapsBtn.setGeometry(QtCore.QRect(20, 313, 235, 51))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.MapsBtn.setFont(font)
        self.MapsBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.MapsBtn.setStyleSheet("background-color: rgba(41, 138, 217, 70);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 1px solid #B4B4B4;\n"
"text-align: left;\n"
"padding-left: 70px;")
        self.MapsBtn.setObjectName("MapsBtn")
        self.MapsImg = QtWidgets.QLabel(parent=self.GlavVrachWidget)
        self.MapsImg.setGeometry(QtCore.QRect(18, 313, 51, 51))
        self.MapsImg.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-radius: 0px;\n"
"border: 0px;")
        self.MapsImg.setText("")
        self.MapsImg.setObjectName("MapsImg")
        self.ContactsText = QtWidgets.QLabel(parent=self.GlavVrachWidget)
        self.ContactsText.setGeometry(QtCore.QRect(20, 400, 235, 121))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(16)
        self.ContactsText.setFont(font)
        self.ContactsText.setStyleSheet("background-color: rgba(41, 138, 217, 70);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 1px solid #B4B4B4;\n"
"text-align: left;\n"
"padding-left: 70px;")
        self.ContactsText.setObjectName("ContactsText")
        self.MailImg = QtWidgets.QLabel(parent=self.GlavVrachWidget)
        self.MailImg.setGeometry(QtCore.QRect(20, 400, 51, 51))
        self.MailImg.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-radius: 0px;\n"
"border: 0px;")
        self.MailImg.setText("")
        self.MailImg.setObjectName("MailImg")
        self.PhoneImg = QtWidgets.QLabel(parent=self.GlavVrachWidget)
        self.PhoneImg.setGeometry(QtCore.QRect(20, 470, 51, 51))
        self.PhoneImg.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-radius: 0px;\n"
"border: 0px;")
        self.PhoneImg.setText("")
        self.PhoneImg.setObjectName("PhoneImg")
        self.NewsMCText = QtWidgets.QLabel(parent=self.HomePage)
        self.NewsMCText.setGeometry(QtCore.QRect(50, 360, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.NewsMCText.setFont(font)
        self.NewsMCText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.NewsMCText.setObjectName("NewsMCText")
        self.NewsMCWidget = QtWidgets.QWidget(parent=self.HomePage)
        self.NewsMCWidget.setGeometry(QtCore.QRect(50, 400, 361, 191))
        self.NewsMCWidget.setStyleSheet("border: 1px solid #B4B4B4;\n"
"border-radius: 15px;")
        self.NewsMCWidget.setObjectName("NewsMCWidget")
        self.label = QtWidgets.QLabel(parent=self.NewsMCWidget)
        self.label.setGeometry(QtCore.QRect(90, 60, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 0px;\n"
"color: #4A4A4A;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.NameMcText = QtWidgets.QLabel(parent=self.HomePage)
        self.NameMcText.setGeometry(QtCore.QRect(135, 40, 291, 85))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.NameMcText.setFont(font)
        self.NameMcText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.NameMcText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.NameMcText.setWordWrap(False)
        self.NameMcText.setObjectName("NameMcText")
        self.MakeRecordBtn = QtWidgets.QPushButton(parent=self.HomePage)
        self.MakeRecordBtn.setGeometry(QtCore.QRect(50, 290, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.MakeRecordBtn.setFont(font)
        self.MakeRecordBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.MakeRecordBtn.setStyleSheet("background-color: #2A8BD9;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #2883CD;\n"
"font-weight: bold;")
        self.MakeRecordBtn.setObjectName("MakeRecordBtn")
        self.stackedWidget.addWidget(self.HomePage)
        self.MyAccountPage = QtWidgets.QWidget()
        self.MyAccountPage.setObjectName("MyAccountPage")
        self.ChangePasswordBtn = QtWidgets.QPushButton(parent=self.MyAccountPage)
        self.ChangePasswordBtn.setGeometry(QtCore.QRect(490, 420, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ChangePasswordBtn.setFont(font)
        self.ChangePasswordBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ChangePasswordBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #2A8BD9;\n"
"border: 1px solid #2883CD;\n"
"border-radius: 15px;\n"
"font-weight: bold;")
        self.ChangePasswordBtn.setObjectName("ChangePasswordBtn")
        self.PhoneNumberHintText = QtWidgets.QLabel(parent=self.MyAccountPage)
        self.PhoneNumberHintText.setGeometry(QtCore.QRect(50, 320, 80, 24))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PhoneNumberHintText.setFont(font)
        self.PhoneNumberHintText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(72, 72, 72);")
        self.PhoneNumberHintText.setObjectName("PhoneNumberHintText")
        self.PhoneNumberText = QtWidgets.QLabel(parent=self.MyAccountPage)
        self.PhoneNumberText.setGeometry(QtCore.QRect(50, 350, 381, 51))
        self.PhoneNumberText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid #B4B4B4;\n"
"border-radius: 15px;\n"
"padding: 5px")
        self.PhoneNumberText.setText("")
        self.PhoneNumberText.setObjectName("PhoneNumberText")
        self.LogOutBtn = QtWidgets.QPushButton(parent=self.MyAccountPage)
        self.LogOutBtn.setGeometry(QtCore.QRect(50, 530, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.LogOutBtn.setFont(font)
        self.LogOutBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.LogOutBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #2A8BD9;\n"
"border: 1px solid #2883CD;\n"
"border-radius: 15px;\n"
"font-weight: bold;")
        self.LogOutBtn.setObjectName("LogOutBtn")
        self.MyAccountText = QtWidgets.QLabel(parent=self.MyAccountPage)
        self.MyAccountText.setGeometry(QtCore.QRect(48, 55, 234, 44))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.MyAccountText.setFont(font)
        self.MyAccountText.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font-weight: bold;")
        self.MyAccountText.setObjectName("MyAccountText")
        self.BackBtn = QtWidgets.QPushButton(parent=self.MyAccountPage)
        self.BackBtn.setGeometry(QtCore.QRect(5, 10, 64, 64))
        self.BackBtn.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.BackBtn.setText("")
        self.BackBtn.setObjectName("BackBtn")
        self.FIOText = QtWidgets.QLabel(parent=self.MyAccountPage)
        self.FIOText.setGeometry(QtCore.QRect(50, 150, 381, 51))
        self.FIOText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid #B4B4B4;\n"
"border-radius: 15px;\n"
"padding: 5px")
        self.FIOText.setText("")
        self.FIOText.setObjectName("FIOText")
        self.SNILSText = QtWidgets.QLabel(parent=self.MyAccountPage)
        self.SNILSText.setGeometry(QtCore.QRect(50, 450, 381, 51))
        self.SNILSText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid #B4B4B4;\n"
"border-radius: 15px;\n"
"padding: 5px")
        self.SNILSText.setText("")
        self.SNILSText.setObjectName("SNILSText")
        self.SNILSHintText = QtWidgets.QLabel(parent=self.MyAccountPage)
        self.SNILSHintText.setGeometry(QtCore.QRect(50, 420, 72, 16))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.SNILSHintText.setFont(font)
        self.SNILSHintText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(72, 72, 72);")
        self.SNILSHintText.setObjectName("SNILSHintText")
        self.BirthdayText = QtWidgets.QLabel(parent=self.MyAccountPage)
        self.BirthdayText.setGeometry(QtCore.QRect(50, 250, 381, 51))
        self.BirthdayText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid #B4B4B4;\n"
"border-radius: 15px;\n"
"padding: 5px")
        self.BirthdayText.setText("")
        self.BirthdayText.setObjectName("BirthdayText")
        self.FIOHintText = QtWidgets.QLabel(parent=self.MyAccountPage)
        self.FIOHintText.setGeometry(QtCore.QRect(50, 120, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.FIOHintText.setFont(font)
        self.FIOHintText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(72, 72, 72);")
        self.FIOHintText.setObjectName("FIOHintText")
        self.Line_2 = QtWidgets.QFrame(parent=self.MyAccountPage)
        self.Line_2.setGeometry(QtCore.QRect(460, 40, 2, 560))
        self.Line_2.setStyleSheet("background-color: #B4B4B4;")
        self.Line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.Line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.Line_2.setObjectName("Line_2")
        self.SettingsText = QtWidgets.QLabel(parent=self.MyAccountPage)
        self.SettingsText.setGeometry(QtCore.QRect(525, 125, 201, 44))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.SettingsText.setFont(font)
        self.SettingsText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.SettingsText.setObjectName("SettingsText")
        self.BirthdateHintText = QtWidgets.QLabel(parent=self.MyAccountPage)
        self.BirthdateHintText.setGeometry(QtCore.QRect(50, 220, 138, 24))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.BirthdateHintText.setFont(font)
        self.BirthdateHintText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(72, 72, 72);")
        self.BirthdateHintText.setObjectName("BirthdateHintText")
        self.label_2 = QtWidgets.QLabel(parent=self.MyAccountPage)
        self.label_2.setGeometry(QtCore.QRect(490, 200, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.PasswordBox = QtWidgets.QLineEdit(parent=self.MyAccountPage)
        self.PasswordBox.setGeometry(QtCore.QRect(490, 240, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PasswordBox.setFont(font)
        self.PasswordBox.setToolTipDuration(-1)
        self.PasswordBox.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid #B4B4B4;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.PasswordBox.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.PasswordBox.setObjectName("PasswordBox")
        self.PasswordBox_2 = QtWidgets.QLineEdit(parent=self.MyAccountPage)
        self.PasswordBox_2.setGeometry(QtCore.QRect(490, 330, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PasswordBox_2.setFont(font)
        self.PasswordBox_2.setToolTipDuration(-1)
        self.PasswordBox_2.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid #B4B4B4;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.PasswordBox_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.PasswordBox_2.setObjectName("PasswordBox_2")
        self.stackedWidget.addWidget(self.MyAccountPage)
        self.MakeRecordPage = QtWidgets.QWidget()
        self.MakeRecordPage.setObjectName("MakeRecordPage")
        self.NameMcTextMakeRecord = QtWidgets.QLabel(parent=self.MakeRecordPage)
        self.NameMcTextMakeRecord.setGeometry(QtCore.QRect(130, 30, 261, 85))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.NameMcTextMakeRecord.setFont(font)
        self.NameMcTextMakeRecord.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.NameMcTextMakeRecord.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.NameMcTextMakeRecord.setWordWrap(False)
        self.NameMcTextMakeRecord.setObjectName("NameMcTextMakeRecord")
        self.LogoImgMakeRecord = QtWidgets.QLabel(parent=self.MakeRecordPage)
        self.LogoImgMakeRecord.setGeometry(QtCore.QRect(28, 24, 101, 101))
        self.LogoImgMakeRecord.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.LogoImgMakeRecord.setText("")
        self.LogoImgMakeRecord.setScaledContents(True)
        self.LogoImgMakeRecord.setObjectName("LogoImgMakeRecord")
        self.DoctorSpecComboBox = QtWidgets.QComboBox(parent=self.MakeRecordPage)
        self.DoctorSpecComboBox.setGeometry(QtCore.QRect(50, 140, 341, 50))
        self.DoctorSpecComboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgba(0,0,0,0);\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    font-size: 15px;\n"
"    color: #2a3b47;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #5fa8d3;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #3498db;\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #c5d8e6;\n"
"    background-color: #f0f6fa;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(resources/icons/arrow-down-lightblue.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 8px;\n"
"    outline: none;\n"
"    selection-background-color: #5fa8d3;\n"
"    selection-color: #ffffff;\n"
"    font-size: 15px;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 28px;\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f2f5f8;\n"
"    width: 8px;\n"
"    margin: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #b6c9d6;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #9fbcd1;\n"
"}")
        self.DoctorSpecComboBox.setCurrentText("")
        self.DoctorSpecComboBox.setObjectName("DoctorSpecComboBox")
        self.DoctorFIOComboBox = QtWidgets.QComboBox(parent=self.MakeRecordPage)
        self.DoctorFIOComboBox.setGeometry(QtCore.QRect(50, 210, 341, 50))
        self.DoctorFIOComboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgba(0,0,0,0);\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    font-size: 15px;\n"
"    color: #2a3b47;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #5fa8d3;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #3498db;\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #c5d8e6;\n"
"    background-color: #f0f6fa;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(resources/icons/arrow-down-lightblue.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 8px;\n"
"    outline: none;\n"
"    selection-background-color: #5fa8d3;\n"
"    selection-color: #ffffff;\n"
"    font-size: 15px;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 28px;\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f2f5f8;\n"
"    width: 8px;\n"
"    margin: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #b6c9d6;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #9fbcd1;\n"
"}")
        self.DoctorFIOComboBox.setCurrentText("")
        self.DoctorFIOComboBox.setObjectName("DoctorFIOComboBox")
        self.widget = QtWidgets.QWidget(parent=self.MakeRecordPage)
        self.widget.setGeometry(QtCore.QRect(50, 280, 341, 321))
        self.widget.setStyleSheet("border: 1px solid #B4B4B4;\n"
"border-radius: 8px;")
        self.widget.setObjectName("widget")
        self.InfoText = QtWidgets.QLabel(parent=self.widget)
        self.InfoText.setGeometry(QtCore.QRect(20, 20, 171, 30))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.InfoText.setFont(font)
        self.InfoText.setStyleSheet("border: 0px;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.InfoText.setObjectName("InfoText")
        self.CreateBtn = QtWidgets.QPushButton(parent=self.widget)
        self.CreateBtn.setGeometry(QtCore.QRect(20, 250, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.CreateBtn.setFont(font)
        self.CreateBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.CreateBtn.setStyleSheet("border: 1px solid #2883CD;\n"
"border-radius: 8px;\n"
"background-color: #2A8BD9;\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;")
        self.CreateBtn.setObjectName("CreateBtn")
        self.InfoWidget = QtWidgets.QPushButton(parent=self.widget)
        self.InfoWidget.setGeometry(QtCore.QRect(20, 70, 301, 161))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.InfoWidget.setFont(font)
        self.InfoWidget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.InfoWidget.setStyleSheet("background-color: rgba(41, 138, 217, 70);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 1px solid #DEDEDE;\n"
"text-align: left;\n"
"padding-left: 100px;")
        self.InfoWidget.setObjectName("InfoWidget")
        self.PassportImg = QtWidgets.QLabel(parent=self.widget)
        self.PassportImg.setGeometry(QtCore.QRect(30, 90, 61, 61))
        self.PassportImg.setStyleSheet("border: 0px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.PassportImg.setText("")
        self.PassportImg.setObjectName("PassportImg")
        self.ClockImg = QtWidgets.QLabel(parent=self.widget)
        self.ClockImg.setGeometry(QtCore.QRect(30, 150, 61, 61))
        self.ClockImg.setStyleSheet("border: 0px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.ClockImg.setText("")
        self.ClockImg.setObjectName("ClockImg")
        self.RecordInfoWidget = QtWidgets.QWidget(parent=self.MakeRecordPage)
        self.RecordInfoWidget.setGeometry(QtCore.QRect(470, 40, 281, 561))
        self.RecordInfoWidget.setStyleSheet("border: 1px solid #B4B4B4;\n"
"border-radius: 8px;")
        self.RecordInfoWidget.setObjectName("RecordInfoWidget")
        self.RecordText = QtWidgets.QLabel(parent=self.RecordInfoWidget)
        self.RecordText.setGeometry(QtCore.QRect(30, 30, 144, 26))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.RecordText.setFont(font)
        self.RecordText.setStyleSheet("border: 0px;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.RecordText.setObjectName("RecordText")
        self.DoctorImg = QtWidgets.QLabel(parent=self.RecordInfoWidget)
        self.DoctorImg.setGeometry(QtCore.QRect(30, 80, 221, 161))
        self.DoctorImg.setText("")
        self.DoctorImg.setObjectName("DoctorImg")
        self.DoctorImg.setStyleSheet("border: 0px;")
        self.DoctorFIOText = QtWidgets.QLabel(parent=self.RecordInfoWidget)
        self.DoctorFIOText.setGeometry(QtCore.QRect(30, 250, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.DoctorFIOText.setFont(font)
        self.DoctorFIOText.setStyleSheet("border: 0px;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.DoctorFIOText.setObjectName("DoctorFIOText")
        self.DoctorSpecText = QtWidgets.QLabel(parent=self.RecordInfoWidget)
        self.DoctorSpecText.setGeometry(QtCore.QRect(30, 290, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(17)
        self.DoctorSpecText.setFont(font)
        self.DoctorSpecText.setStyleSheet("color: #4A4A4A;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.DoctorSpecText.setObjectName("DoctorSpecText")
        self.RecordTimeComboBox = QtWidgets.QComboBox(parent=self.RecordInfoWidget)
        self.RecordTimeComboBox.setGeometry(QtCore.QRect(30, 480, 221, 50))
        self.RecordTimeComboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgba(0,0,0,0);\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    font-size: 15px;\n"
"    color: #2a3b47;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #5fa8d3;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #3498db;\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #c5d8e6;\n"
"    background-color: #f0f6fa;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(resources/icons/arrow-down-lightblue.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 8px;\n"
"    outline: none;\n"
"    selection-background-color: #5fa8d3;\n"
"    selection-color: #ffffff;\n"
"    font-size: 15px;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 28px;\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f2f5f8;\n"
"    width: 8px;\n"
"    margin: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #b6c9d6;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #9fbcd1;\n"
"}")
        self.RecordTimeComboBox.setObjectName("RecordTimeComboBox")
        self.RecordDateComboBox = QtWidgets.QComboBox(parent=self.RecordInfoWidget)
        self.RecordDateComboBox.setGeometry(QtCore.QRect(30, 380, 221, 50))
        self.RecordDateComboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgba(0,0,0,0);\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    font-size: 15px;\n"
"    color: #2a3b47;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #5fa8d3;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #3498db;\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #c5d8e6;\n"
"    background-color: #f0f6fa;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(resources/icons/arrow-down-lightblue.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    background-color: #f7fbff;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c5d8e6;\n"
"    border-radius: 8px;\n"
"    outline: none;\n"
"    selection-background-color: #5fa8d3;\n"
"    selection-color: #ffffff;\n"
"    font-size: 15px;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 28px;\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f2f5f8;\n"
"    width: 8px;\n"
"    margin: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #b6c9d6;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #9fbcd1;\n"
"}")
        self.RecordDateComboBox.setObjectName("RecordDateComboBox")
        self.RecordTimeText = QtWidgets.QLabel(parent=self.RecordInfoWidget)
        self.RecordTimeText.setGeometry(QtCore.QRect(30, 440, 114, 31))
        self.RecordTimeText.setStyleSheet("font-family: Iowan Old Style;\n"
"color: rgb(0, 0, 0);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"border: 0px;")
        self.RecordTimeText.setObjectName("RecordTimeText")
        self.RecordDateText = QtWidgets.QLabel(parent=self.RecordInfoWidget)
        self.RecordDateText.setGeometry(QtCore.QRect(30, 340, 111, 31))
        self.RecordDateText.setStyleSheet("font-family: Iowan Old Style;\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"border: 0px;\n"
"color: rgb(0, 0, 0);")
        self.RecordDateText.setObjectName("RecordDateText")
        self.LineMakeRecord = QtWidgets.QFrame(parent=self.MakeRecordPage)
        self.LineMakeRecord.setGeometry(QtCore.QRect(430, 39, 2, 561))
        self.LineMakeRecord.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.LineMakeRecord.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.LineMakeRecord.setObjectName("LineMakeRecord")
        self.LineMakeRecord.setStyleSheet("background-color: #B4B4B4;")
        self.BackBtnMakeRecord = QtWidgets.QPushButton(parent=self.MakeRecordPage)
        self.BackBtnMakeRecord.setGeometry(QtCore.QRect(0, 0, 64, 64))
        self.BackBtnMakeRecord.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.BackBtnMakeRecord.setText("")
        self.BackBtnMakeRecord.setObjectName("BackBtnMakeRecord")
        self.stackedWidget.addWidget(self.MakeRecordPage)
        self.MyRecordsPage = QtWidgets.QWidget()
        self.MyRecordsPage.setObjectName("MyRecordsPage")
        self.TitleLabel = QtWidgets.QLabel(parent=self.MyRecordsPage)
        self.TitleLabel.setGeometry(QtCore.QRect(298, 50, 175, 31))
        self.TitleLabel.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font-size: 30px;\n"
"font-weight: bold;")
        self.TitleLabel.setObjectName("TitleLabel")
        self.RecordsScrollArea = QtWidgets.QScrollArea(parent=self.MyRecordsPage)
        self.RecordsScrollArea.setGeometry(QtCore.QRect(20, 110, 741, 481))
        self.RecordsScrollArea.setStyleSheet("border: 0px;")
        self.RecordsScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.RecordsScrollArea.setWidgetResizable(True)
        self.RecordsScrollArea.setObjectName("RecordsScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 741, 481))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.RecordsContainer = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.RecordsContainer.setGeometry(QtCore.QRect(10, 10, 721, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RecordsContainer.sizePolicy().hasHeightForWidth())
        self.RecordsContainer.setSizePolicy(sizePolicy)
        self.RecordsContainer.setObjectName("RecordsContainer")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.RecordsContainer)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 701, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_4.setSpacing(12)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.AppointmentCardExample = QtWidgets.QFrame(parent=self.gridLayoutWidget)
        self.AppointmentCardExample.setMinimumSize(QtCore.QSize(0, 110))
        self.AppointmentCardExample.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 1px solid #e1e6ef;\n"
"    border-radius: 10px;\n"
"}")
        self.AppointmentCardExample.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.AppointmentCardExample.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.AppointmentCardExample.setObjectName("AppointmentCardExample")
        self.DoctorPhoto = QtWidgets.QLabel(parent=self.AppointmentCardExample)
        self.DoctorPhoto.setGeometry(QtCore.QRect(20, 20, 161, 101))
        self.DoctorPhoto.setText("")
        self.DoctorPhoto.setObjectName("DoctorPhoto")
        self.CancelButton = QtWidgets.QPushButton(parent=self.AppointmentCardExample)
        self.CancelButton.setGeometry(QtCore.QRect(30, 140, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.CancelButton.setFont(font)
        self.CancelButton.setStyleSheet("border: 1px solid #2883CD;\n"
"border-radius: 8px;\n"
"background-color: #2A8BD9;\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;")
        self.CancelButton.setObjectName("CancelButton")
        self.DoctorNameLabel = QtWidgets.QLabel(parent=self.AppointmentCardExample)
        self.DoctorNameLabel.setGeometry(QtCore.QRect(190, 20, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.DoctorNameLabel.setFont(font)
        self.DoctorNameLabel.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.DoctorNameLabel.setWordWrap(True)
        self.DoctorNameLabel.setObjectName("DoctorNameLabel")
        self.DoctorSpecLabel = QtWidgets.QLabel(parent=self.AppointmentCardExample)
        self.DoctorSpecLabel.setGeometry(QtCore.QRect(190, 80, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.DoctorSpecLabel.setFont(font)
        self.DoctorSpecLabel.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.DoctorSpecLabel.setWordWrap(True)
        self.DoctorSpecLabel.setObjectName("DoctorSpecLabel")
        self.DateTimeLabel = QtWidgets.QLabel(parent=self.AppointmentCardExample)
        self.DateTimeLabel.setGeometry(QtCore.QRect(190, 140, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.DateTimeLabel.setFont(font)
        self.DateTimeLabel.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.DateTimeLabel.setWordWrap(True)
        self.DateTimeLabel.setObjectName("DateTimeLabel")
        self.gridLayout_4.addWidget(self.AppointmentCardExample, 0, 0, 1, 1)
        self.RecordsScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.BackBtnMyRecords = QtWidgets.QPushButton(parent=self.MyRecordsPage)
        self.BackBtnMyRecords.setGeometry(QtCore.QRect(0, 0, 64, 64))
        self.BackBtnMyRecords.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.BackBtnMyRecords.setText("")
        self.BackBtnMyRecords.setObjectName("BackBtnMyRecords")
        self.stackedWidget.addWidget(self.MyRecordsPage)
        HomeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(HomeWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "Home"))
        self.MyRecordsBtn.setText(_translate("HomeWindow", "Просмотреть записи"))
        self.MyAccountBtn.setText(_translate("HomeWindow", "Мой аккаунт"))
        self.GlavVrachText.setText(_translate("HomeWindow", "Наш главный врач"))
        self.GlavVrachFIOText.setText(_translate("HomeWindow", "Иван Кравцов"))
        self.GlavVrachSpecText.setText(_translate("HomeWindow", "Главврач"))
        self.MapsBtn.setText(_translate("HomeWindow", "г. Москва, ул. Большая\n"
"поляна, д14к2"))
        self.ContactsText.setText(_translate("HomeWindow", "Info@clinic.mc\n"
"\n"
"\n"
"+7 (945) 743-80-23"))
        self.NewsMCText.setText(_translate("HomeWindow", "Новости поликлинники"))
        self.label.setText(_translate("HomeWindow", "Скоро здесь появятся новости"))
        self.NameMcText.setText(_translate("HomeWindow", "Медицинский\n"
"центр"))
        self.MakeRecordBtn.setText(_translate("HomeWindow", "Записаться"))
        self.ChangePasswordBtn.setText(_translate("HomeWindow", " Сохранить"))
        self.PhoneNumberHintText.setText(_translate("HomeWindow", "Телефон"))
        self.LogOutBtn.setText(_translate("HomeWindow", "Выйти"))
        self.MyAccountText.setText(_translate("HomeWindow", "Мой аккаунт"))
        self.SNILSHintText.setText(_translate("HomeWindow", "СНИЛС"))
        self.FIOHintText.setText(_translate("HomeWindow", "ФИО"))
        self.SettingsText.setText(_translate("HomeWindow", "Настройки"))
        self.BirthdateHintText.setText(_translate("HomeWindow", "Дата рождения"))
        self.label_2.setText(_translate("HomeWindow", "Сменить пароль"))
        self.PasswordBox.setPlaceholderText(_translate("HomeWindow", "Новый пароль"))
        self.PasswordBox_2.setPlaceholderText(_translate("HomeWindow", "Подтвердите пароль"))
        self.NameMcTextMakeRecord.setText(_translate("HomeWindow", "Запись на приём"))
        self.InfoText.setText(_translate("HomeWindow", "Информация"))
        self.CreateBtn.setText(_translate("HomeWindow", "Создать запись"))
        self.InfoWidget.setText(_translate("HomeWindow", "Не забудьте СНИЛС и\n"
"паспорт\n"
"\n"
"Приходите за 5 минут\n"
"до записи"))
        self.RecordText.setText(_translate("HomeWindow", "Ваша запись"))
        self.DoctorFIOText.setText(_translate("HomeWindow", "Иван Петров"))
        self.DoctorSpecText.setText(_translate("HomeWindow", "Терапевт"))
        self.RecordTimeText.setText(_translate("HomeWindow", "Время записи:"))
        self.RecordDateText.setText(_translate("HomeWindow", "Дата записи:"))
        self.TitleLabel.setText(_translate("HomeWindow", "Мои записи"))
        self.CancelButton.setText(_translate("HomeWindow", "Отменить"))
        self.DoctorNameLabel.setText(_translate("HomeWindow", "<html><head/><body><p align=\"center\">Семёнов Никита</p></body></html>"))
        self.DoctorSpecLabel.setText(_translate("HomeWindow", "<html><head/><body><p align=\"center\">Практолог</p></body></html>"))
        self.DateTimeLabel.setText(_translate("HomeWindow", "<html><head/><body><p align=\"center\">00.00.0000 00:00</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomeWindow = QtWidgets.QMainWindow()
    ui = Ui_HomeWindow()
    ui.setupUi(HomeWindow)
    HomeWindow.show()
    sys.exit(app.exec())
