# Form implementation generated from reading ui file 'ErrorWindowUi.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ErrorGosWindow(object):
    def setupUi(self, ErrorGosWindow):
        ErrorGosWindow.setObjectName("ErrorGosWindow")
        ErrorGosWindow.resize(800, 640)
        ErrorGosWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=ErrorGosWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.BackgroundImg = QtWidgets.QLabel(parent=self.centralwidget)
        self.BackgroundImg.setText("")
        self.BackgroundImg.setScaledContents(True)
        self.BackgroundImg.setObjectName("BackgorundImg")
        self.gridLayout.addWidget(self.BackgroundImg, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(301, 481))
        self.widget.setMaximumSize(QtCore.QSize(301, 481))
        self.widget.setStyleSheet("background-color: rgba(255, 255, 255, 135);\n"
"border-radius: 20px;")
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ErrorText = QtWidgets.QLabel(parent=self.widget)
        self.ErrorText.setGeometry(QtCore.QRect(90, 160, 116, 51))
        font = QtGui.QFont()
        font.setPointSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.ErrorText.setFont(font)
        self.ErrorText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;")
        self.ErrorText.setObjectName("ErrorText")
        self.CloseBtn = QtWidgets.QPushButton(parent=self.widget)
        self.CloseBtn.setGeometry(QtCore.QRect(25, 375, 250, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.CloseBtn.setFont(font)
        self.CloseBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.CloseBtn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #007DAB;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color:  #2A8BD9;\n"
"    font-weight: bold;\n"
"}")
        self.CloseBtn.setObjectName("CloseBtn")
        self.ErrorText2 = QtWidgets.QLabel(parent=self.widget)
        self.ErrorText2.setGeometry(QtCore.QRect(30, 235, 241, 91))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(16)
        self.ErrorText2.setFont(font)
        self.ErrorText2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(189, 189, 189);\n"
"color: rgb(109, 109, 109);")
        self.ErrorText2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ErrorText2.setWordWrap(True)
        self.ErrorText2.setObjectName("ErrorText2")
        self.ErrorImg = QtWidgets.QLabel(parent=self.widget)
        self.ErrorImg.setGeometry(QtCore.QRect(100, 40, 100, 100))
        self.ErrorImg.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.ErrorImg.setText("")
        self.ErrorImg.setObjectName("ErrorImg")
        ErrorGosWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ErrorGosWindow)
        QtCore.QMetaObject.connectSlotsByName(ErrorGosWindow)

    def retranslateUi(self, ErrorGosWindow):
        _translate = QtCore.QCoreApplication.translate
        ErrorGosWindow.setWindowTitle(_translate("ErrorGosWindow", "Вход через Госуслуги"))
        self.ErrorText.setText(_translate("ErrorGosWindow", "Ошибка"))
        self.CloseBtn.setText(_translate("ErrorGosWindow", "Закрыть"))
        self.ErrorText2.setText(_translate("ErrorGosWindow", "Вход через Госуслуги временно не работает. Попробуйте позже. Приносим свои извинения за неудобства."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ErrorGosWindow = QtWidgets.QMainWindow()
    ui = Ui_ErrorGosWindow()
    ui.setupUi(ErrorGosWindow)
    ErrorGosWindow.show()
    sys.exit(app.exec())
