# Form implementation generated from reading ui file 'ForgotPasswordWindowUi.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ForgotPasswordWindow(object):
    def setupUi(self, ForgotPasswordWindow):
        ForgotPasswordWindow.setObjectName("ForgotPasswordWindow")
        ForgotPasswordWindow.resize(800, 640)
        self.centralwidget = QtWidgets.QWidget(parent=ForgotPasswordWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.BackgroundImg = QtWidgets.QLabel(parent=self.centralwidget)
        self.BackgroundImg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.BackgroundImg.setText("")
        self.BackgroundImg.setScaledContents(True)
        self.BackgroundImg.setObjectName("BackgroundImg")
        self.gridLayout.addWidget(self.BackgroundImg, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(361, 451))
        self.widget.setMaximumSize(QtCore.QSize(361, 451))
        self.widget.setStyleSheet("background-color: rgba(255, 255, 255, 135);\n"
"border-radius: 20px;")
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.GivePassBtn = QtWidgets.QPushButton(parent=self.widget)
        self.GivePassBtn.setGeometry(QtCore.QRect(80, 300, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.GivePassBtn.setFont(font)
        self.GivePassBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.GivePassBtn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #2883CD;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: #2A8BD9;\n"
"    font-weight: bold;\n"
"}")
        self.GivePassBtn.setObjectName("GivePassBtn")
        self.LoginBox = QtWidgets.QLineEdit(parent=self.widget)
        self.LoginBox.setGeometry(QtCore.QRect(25, 230, 308, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LoginBox.setFont(font)
        self.LoginBox.setToolTipDuration(-1)
        self.LoginBox.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid #E9E9E9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.LoginBox.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.LoginBox.setPlaceholderText("")
        self.LoginBox.setObjectName("LoginBox")
        self.HintText = QtWidgets.QLabel(parent=self.widget)
        self.HintText.setGeometry(QtCore.QRect(34, 170, 290, 51))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.HintText.setFont(font)
        self.HintText.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.HintText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.HintText.setWordWrap(True)
        self.HintText.setObjectName("HintText")
        self.NameMCText = QtWidgets.QLabel(parent=self.widget)
        self.NameMCText.setGeometry(QtCore.QRect(130, 26, 181, 61))
        font = QtGui.QFont()
        font.setFamily(".Lucida Grande UI")
        font.setPointSize(25)
        font.setKerning(True)
        self.NameMCText.setFont(font)
        self.NameMCText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.NameMCText.setWordWrap(True)
        self.NameMCText.setObjectName("NameMCText")
        self.LogoImg = QtWidgets.QLabel(parent=self.widget)
        self.LogoImg.setGeometry(QtCore.QRect(30, 10, 100, 100))
        self.LogoImg.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.LogoImg.setText("")
        self.LogoImg.setPixmap(QtGui.QPixmap("resources/logo.png"))
        self.LogoImg.setScaledContents(True)
        self.LogoImg.setObjectName("LogoImg")
        self.ForgotText = QtWidgets.QLabel(parent=self.widget)
        self.ForgotText.setGeometry(QtCore.QRect(60, 100, 240, 61))
        font = QtGui.QFont()
        font.setFamily("Iowan Old Style")
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.ForgotText.setFont(font)
        self.ForgotText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.ForgotText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ForgotText.setObjectName("ForgotText")
        self.BackBtn = QtWidgets.QPushButton(parent=self.widget)
        self.BackBtn.setGeometry(QtCore.QRect(80, 370, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.BackBtn.setFont(font)
        self.BackBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.BackBtn.setStyleSheet("QPushButton {\n"
"    color: #2A8BD9;\n"
"    border: 1px solid #2883CD;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}")
        self.BackBtn.setObjectName("BackBtn")
        ForgotPasswordWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ForgotPasswordWindow)
        QtCore.QMetaObject.connectSlotsByName(ForgotPasswordWindow)

    def retranslateUi(self, ForgotPasswordWindow):
        _translate = QtCore.QCoreApplication.translate
        ForgotPasswordWindow.setWindowTitle(_translate("ForgotPasswordWindow", "Забыли пароль"))
        self.GivePassBtn.setText(_translate("ForgotPasswordWindow", "Вспомнить"))
        self.HintText.setWhatsThis(_translate("ForgotPasswordWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.HintText.setText(_translate("ForgotPasswordWindow", "Не беда, мы поможем вспомнить!"))
        self.NameMCText.setText(_translate("ForgotPasswordWindow", "Медицинский центр"))
        self.ForgotText.setText(_translate("ForgotPasswordWindow", "Забыли пароль?"))
        self.BackBtn.setText(_translate("ForgotPasswordWindow", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ForgotPasswordWindow = QtWidgets.QMainWindow()
    ui = Ui_ForgotPasswordWindow()
    ui.setupUi(ForgotPasswordWindow)
    ForgotPasswordWindow.show()
    sys.exit(app.exec())
